# Generated by Django 4.0.3 on 2022-04-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_user_balance_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='discription',
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(default='some operations', max_length=255, verbose_name='Description'),
        ),
    ]
